# Generated by Django 3.0.5 on 2021-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ip', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
